<a href="https://colab.research.google.com/github/mishrayuthika05-ui/fakenewsdetecter/blob/main/fakenewsdetecter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the dependecies

In [ ]:
import numpy as np
import pandas as pd
import re

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

data pre processing

In [ ]:
# loading the dataset to a pandas DataFrame
news_dataset = pd.read_csv('/content/test.csv')

In [ ]:
 # rows and columns
news_dataset.shape

(1267, 2)

In [ ]:
news_dataset.head()

   label                                               news
0   True  Building a wall on the U.S.-Mexico border will...
1  False  Wisconsin is on pace to double the number of l...
2  False  Says John McCain has done nothing to help the ...
3   True  Suzanne Bonamici supports a plan that will cut...
4  False  When asked by a reporter whether hes at the ce...

In [ ]:
news_dataset.isnull().sum()

label    0
news     0
dtype: int64

In [ ]:
news_dataset = news_dataset.fillna('')

In [ ]:
x = news_dataset['news']
y = news_dataset['label']

In [ ]:
print(x)
print(y)

0       Building a wall on the U.S.-Mexico border will...
1       Wisconsin is on pace to double the number of l...
2       Says John McCain has done nothing to help the ...
3       Suzanne Bonamici supports a plan that will cut...
4       When asked by a reporter whether hes at the ce...
                              ...
1262    Says his budget provides the highest state fun...
1263                      Ive been here almost every day.
1264    In the early 1980s, Sen. Edward Kennedy secret...
1265    Says an EPA permit languished under Strickland...
1266    Says the governor is going around the state ta...
Name: news, Length: 1267, dtype: object
0        True
1       False
2       False
3        True
4       False
        ...
1262     True
1263    False
1264    False
1265    False
1266    False
Name: label, Length: 1267, dtype: bool

stemming:
process of removing word from its root word.



example:
actor,actress,acting
rootword = act

In [ ]:
Port_stem = PorterStemmer()

In [ ]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [Port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [ ]:
x = news_dataset['news'].values
y = news_dataset['label'].values

In [ ]:
print(x)

['Building a wall on the U.S.-Mexico border will take literally years.'
 'Wisconsin is on pace to double the number of layoffs this year.'
 'Says John McCain has done nothing to help the vets.' ...
 'In the early 1980s, Sen. Edward Kennedy secretly offered to help Soviet leaders counter the Reagan administrations position on nuclear disarmament.'
 'Says an EPA permit languished under Strickland but his new EPA director got it done in two days.'
 'Says the governor is going around the state talking about [how] we should fund an income tax cut that benefits higher income earners and not lower income earners']

In [ ]:
print(y)

[ True False False ... False False False]

In [ ]:
y.shape

(1267,)

In [ ]:
vectorizer = TfidfVectorizer()
vectorizer.fit(x)

x = vectorizer.transform(x)

In [ ]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20827 stored elements and shape (1267, 4348)>
  Coords	Values
  (0, 625)	0.34890394238837374
  (0, 674)	0.4277800907422545
  (0, 2346)	0.3857008974389432
  (0, 2510)	0.3857008974389432
  (0, 2751)	0.1830509977747802
  (0, 3848)	0.33007522960109986
  (0, 3919)	0.09242464296519344
  (0, 4206)	0.3610861472959093
  (0, 4280)	0.25119908124721924
  (0, 4333)	0.23077271195210952
  (1, 1288)	0.41168448394327556
  (1, 2110)	0.16759795190823457
  (1, 2276)	0.453904055831189
  (1, 2704)	0.3353787328844903
  (1, 2722)	0.12123142437736349
  (1, 2751)	0.18366166632520645
  (1, 2823)	0.453904055831189
  (1, 3919)	0.0927329768362421
  (1, 3941)	0.24776095660563588
  (1, 3970)	0.12387435380251637
  (1, 4290)	0.297673075134241
  (1, 4331)	0.2356320355776743
  (2, 1283)	0.3796357792665024
  (2, 1853)	0.21352428654741779
  (2, 1888)	0.3796357792665024
  :	:
  (1265, 4081)	0.17721447445499836
  (1266, 215)	0.14183731621581738
  (1266, 358)	0.135174590343678
  (1266, 361)	0.07953538159951441
  (1266, 412)	0.20771418030564703
  (1266, 562)	0.1957633776190469
  (1266, 1093)	0.16248333886364555
  (1266, 1335)	0.45292949701335816
  (1266, 1686)	0.18448948979004967
  (1266, 1757)	0.16126479927445234
  (1266, 1769)	0.16506200673141472
  (1266, 1903)	0.18217780457656818
  (1266, 1967)	0.19929360242172162
  (1266, 2025)	0.5127117502427129
  (1266, 2110)	0.0921944584007264
  (1266, 2392)	0.19929360242172162
  (1266, 2690)	0.12214285050289476
  (1266, 3489)	0.08113885242408098
  (1266, 3588)	0.18697256231242268
  (1266, 3724)	0.11697785534434145
  (1266, 3857)	0.22646474850667908
  (1266, 3870)	0.1260893060722549
  (1266, 3915)	0.09407380025003331
  (1266, 3919)	0.10202352090776819
  (1266, 4235)	0.11998041340181101

spliting a dataset to training and testing the data

In [ ]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

training the model:logistic regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

evaluation

In [ ]:
#accuracy score on the training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [ ]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.910167818361303

In [ ]:
#accuracy score on the test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [ ]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.5708661417322834

making a predictive system

In [ ]:
x_new = x_test[1]

prediction = model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print('The news is Real')
else:
  print('The news is Fake')

[ True]
The news is Fake

In [ ]:
print(y_test[1])

True